// Package tracing — long-lifecycle correlation helpers.
//
// REQ-138 (#320): an issue or PR's `root_trace_id` is persisted at first
// sighting (REQ-137 / #317) and reused across every subsequent operation
// on that issue. Spans can't stay open for hours, so correlation is done
// by minting a fresh span_id under the persisted trace_id and emitting
// each operation's span as a child of that synthetic parent.
//
// The two helpers in this file are the only sanctioned way to wire that
// reuse:
//
//   - ContextFromTraceID(ctx, traceIDHex): wraps a remote SpanContext
//     into ctx so the next tracing.Start (or otel.Tracer().Start) emits a
//     span carrying the persisted trace_id. Empty/invalid trace_id is a
//     no-op so call sites can blindly load-and-wrap without branching.
//
//   - SetIssueAttrs(span, ...): stamps every span in the affected paths
//     with the mandatory business attributes (issue.id, issue.number,
//     repo, pr.number, agent.role, agent.runtime). Centralising the keys
//     here keeps the schema discoverable and avoids drift across call
//     sites.
//
// Cross-process TRACEPARENT injection (sandbox / agent subprocess) is
// explicitly out of scope; it lands in v0.6.

package tracing

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"log"
	"strconv"
	"strings"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

// ContextFromTraceID returns a derived context whose parent SpanContext
// carries the supplied trace_id and a freshly generated span_id, so any
// span subsequently started from the returned context is rooted under
// the persisted trace.
//
// Behaviour contract:
//
//   - traceIDHex == "" → returns ctx unchanged. Common case: the store
//     row predates REQ-137 migration and surfaces ''.
//   - traceIDHex is malformed (not 32 lowercase hex, or all-zero) →
//     returns ctx unchanged and logs a single-line warning. Callers
//     never see an error so the hot path stays branch-free.
//   - traceIDHex valid → wraps a remote SpanContext (IsRemote=true,
//     non-sampled flag — sampling decision rolls forward from the global
//     provider when the child span is started) into ctx via
//     trace.ContextWithSpanContext.
//
// The span_id is generated by the global TracerProvider's IDGenerator;
// when no SDK is installed (tracetest setup not done) we fall back to a
// deterministic-but-non-zero span_id derived from the trace_id so the
// returned SpanContext stays valid.
func ContextFromTraceID(ctx context.Context, traceIDHex string) context.Context {
	tid, ok := parseTraceID(traceIDHex)
	if !ok {
		if strings.TrimSpace(traceIDHex) != "" {
			log.Printf("[tracing] malformed root_trace_id %q — span will start a new trace", traceIDHex)
		}
		return ctx
	}
	sid := freshSpanID(tid)
	sc := trace.NewSpanContext(trace.SpanContextConfig{
		TraceID:    tid,
		SpanID:     sid,
		TraceFlags: trace.FlagsSampled,
		Remote:     true,
	})
	return trace.ContextWithSpanContext(ctx, sc)
}

// SetIssueAttrs stamps the standard business attributes on span. Pass
// zero-values for fields that are not applicable (e.g. prNumber=0 for
// pure-issue work, role/runtime="" outside the dispatch path); the
// helper skips empties so spans stay clean.
//
// The attribute keys are stable contract — Jaeger/Tempo dashboards and
// the OTel collector pipeline filter on them. Do not rename without
// coordinating with the AegisLab collector config.
func SetIssueAttrs(span trace.Span, repo string, issueNum int, prNum int, role, runtime string) {
	if span == nil || !span.IsRecording() {
		return
	}
	attrs := make([]attribute.KeyValue, 0, 6)
	if strings.TrimSpace(repo) != "" {
		attrs = append(attrs, attribute.String("repo", repo))
	}
	if issueNum > 0 {
		// issue.id is the workbuddy logical id; in this single-repo-per-row
		// world we render it as "repo#num" for global uniqueness in the
		// trace view, with issue.number kept as the numeric for filtering.
		attrs = append(attrs,
			attribute.String("issue.id", issueIDKey(repo, issueNum)),
			attribute.Int("issue.number", issueNum),
		)
	}
	if prNum > 0 {
		attrs = append(attrs, attribute.Int("pr.number", prNum))
	}
	if strings.TrimSpace(role) != "" {
		attrs = append(attrs, attribute.String("agent.role", role))
	}
	if strings.TrimSpace(runtime) != "" {
		attrs = append(attrs, attribute.String("agent.runtime", runtime))
	}
	if len(attrs) > 0 {
		span.SetAttributes(attrs...)
	}
}

func issueIDKey(repo string, issueNum int) string {
	if repo == "" {
		return ""
	}
	return repo + "#" + strconv.Itoa(issueNum)
}

func parseTraceID(s string) (trace.TraceID, bool) {
	s = strings.TrimSpace(s)
	if len(s) != 32 {
		return trace.TraceID{}, false
	}
	var raw [16]byte
	n, err := hex.Decode(raw[:], []byte(s))
	if err != nil || n != 16 {
		return trace.TraceID{}, false
	}
	tid := trace.TraceID(raw)
	if !tid.IsValid() {
		return trace.TraceID{}, false
	}
	return tid, true
}

// freshSpanID returns a usable span_id for the synthetic parent
// SpanContext. The value is not emitted as a real span; it only needs
// to be non-zero so the SDK accepts the SpanContext as a valid parent.
// crypto/rand keeps us free of the global IDGenerator (which would
// require allocating a throwaway real span — undesirable in tracetest
// runs where it would inflate captured span counts).
func freshSpanID(tid trace.TraceID) trace.SpanID {
	var s [8]byte
	if _, err := rand.Read(s[:]); err == nil {
		sid := trace.SpanID(s)
		if sid.IsValid() {
			return sid
		}
	}
	// Fallback: fold the trace_id bytes into 8 to get a deterministic
	// non-zero span_id when crypto/rand fails (extraordinary).
	for i := 0; i < 16; i++ {
		s[i%8] ^= tid[i]
	}
	if s == ([8]byte{}) {
		s[7] = 1
	}
	return trace.SpanID(s)
}
